Hack/urls.py
from django.contrib import admin
from django.urls import path , include , re_path
from blog import views
from django.conf.urls import url
from django.contrib import admin
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    #path(r'^user/', include('blog.urls')),

    path('newAccount/' ,include('blog.urls')),
    path('newBack/' ,include('blog.urls')),

    path('log/' ,include('blog.urls')),
    path('logBack/' ,include('blog.urls')),

    url('profile/<slug:slug>/', include('blog.urls')),
    path('ask/', include('blog.urls')),
    path('answer/', include('blog.urls')),
    path('logoutBack/', include('blog.urls')),

  #  path('' ,include('blog/urls.py')),
#    path('new1/' ,include('blog.urls')),

]

accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import auth_login , auth_logout #4:57

urlpatterns =[
#    path('acc/' , views.home2 , name='home2'),
    path('login0/' , views.home2 , name='login0'),

]

blog/urls.py
from django.urls import path 
from . import views
from django.conf.urls import url
from .views import PostCreateView
urlpatterns =[
    path('' , views.home , name='home'),
    path('newAccount/' , views.new1, name='new1'),
    path('newBack/' , views.newBack, name='newBack'),

    path('log/' , views.login, name='log1'),
    path('logBack/' , views.logBack, name='logBack'),
    #url(r'profile/(?P<username>[a-zA-Z0-9]+)$', views.get_user_profile),

    url('profile/<slug:slug>/' , views.profileD, name='pro1'),
    path('ask/',views.ask, name='ask1'),
   # path('ask/',PostCreateView.as_view(), name='ask1'),
    path('answer',views.answer,name='ans1'),
    path('logoutBack/', views.logoutBack , name='out1')

   # re_path(r"^profile/(?P<username>)/$" , views.profile, name='pro1'),


]

accounts/models.py
from django.db import models

# Create your models here.

blog/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
import datetime
from django.utils.text import slugify
from django.db.models.signals import post_save
from django.utils import timezone
from django.urls import reverse


class profile(models.Model):
    user = models.OneToOneField(User , on_delete=models.CASCADE)
    slug =models.SlugField(null=True , blank=True)
    email=models.CharField(blank=True , max_length=100)
    

def save(self , *args , **kwargs):
    if not self.slug:
        self.slug = slugify(self.user)
    super(profile , self).save( *args , **kwargs)

    def __str__(self):  # part2 10:00
        return self.first_name


def CProfile(sender , **kwargs):
    if kwargs['created']:
        user_profile = profile.objects.create(user=kwargs['instance'])

post_save.connect(CProfile, sender=User)
 
 
 #########  اضافة سؤال #########


class post(models.Model):
    title= models.CharField(max_length=100)
    text1= models.TextField(max_length=1000)
    postDate =models.DateTimeField(default=timezone.now , null=True , blank=True)
    phone_number = models.CharField(max_length=11,null=True , blank=True)
    userD= models.ForeignKey(User, on_delete=models.CASCADE) #هذا اذا اليوزر انحذف ينحذف الجدول
    img = models.ImageField(upload_to ='pics' , null=True , blank=True)

    def __str__(self):
        return self.title
    def get_absolute_url(self):
        return reverse('newAccount/' , args=[self.pk])
    class Meta:
        ordering = ('-postDate',)


class comment(models.Model):
    name = models.CharField(max_length=100)
    text2 = models.TextField(max_length=2000)
    comT =models.DateTimeField(default=timezone.now , null=True , blank=True)
    post = models.ForeignKey(post, on_delete=models.CASCADE, related_name='comments')

    def __str__(self):
        return self.name

user/models.py
from django.db import models

# Create your models here.

blog/forms.py
from django import forms
from .models import post


class PostCreateForm(forms.ModelForm):
    title = forms.CharField(label='عنوان التدوينة')
    content = forms.CharField(label='نص التدوينة', widget=forms.Textarea)

    class Meta:
        model = post
        fields = ['title', 'content']

accounts/views.py
from django.shortcuts import render
# Create your views here.


def home2(request):
    return render(request ,'account/page.html' )

blog/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from django.http import HttpResponse , HttpResponseRedirect
from django.contrib.auth import authenticate 
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from .models import profile
from django.shortcuts import get_object_or_404
from .models import post , comment
from django.contrib import messages
from django.contrib.auth.models import User
from django.views.generic import CreateView
from .forms import PostCreateForm


# Create your views here

def home(request): 
    return render(request ,'blog/index.html' , {'title' : 'Home'})

def new1(request):
    return render(request , 'blog/register.html')

def login(request):
    return render(request , 'blog/login.html')

def profileD(request , username):
    return render(request , 'blog/survey.html')
    profile = profile.objects.get(username)#slug=slug)
    context = {
        'profile' : profile ,
    }
    return render(request , 'blog/survey.html')


def ask(request):
 #   post2 = post.objects.PostCreateView()
    return render(request , 'blog/application.html')
    
def answer(request):
    post1 = post.objects.get()
    com1 = comment.objects.get()
    context = {
        "post1":post1 , 
        "com1" :com1,
    
    }
    return render(request, 'blog/signup.html',context )


#from django.shortcuts import render
####123###
def get_user_profile(request, username):
    user = User.objects.get(username=username)
    return render(request, 'blog/survey.html', {"user":user})




def newBack(request): #مستخدم جديد
    try:
        user=User.objects.create_user(request.POST['username'], request.POST['email'], request.POST['password'])
        user.first_name=request.POST['first_name']
        user.last_name=request.POST['last_name']
        user.age=request.POST['age']
        user.age=request.POST['phone']
        user.save()
        messages.success(request,' شكراً لك على التسجيل  ')
        return render(request , 'blog/survey.html' , {'user':user})

    except:
        return render(request , 'blog/login3.html')


class PostCreateView(CreateView):
    model = post
    template_name = 'blog/application.html'
    field =['title' , 'text1']
    form_class = PostCreateForm

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


def logBack(request):
    u=request.POST['username']
    p=request.POST['password']
    re=authenticate(username=u, password=p)

    if re is not None:
        print('log in')
        auth_login(request,re)
       # link='/profile/'+str(re)
        #return HttpResponseRedirect(link)
        return render(request , 'blog/survey.html')
    else:
        return render(request , 'blog/login2.html')

def logoutBack(request):
    auth_logout(request)
    print('log in')
    return render(request ,'blog/index.html' , {'title' : 'Home'})

user/views.py
from django.shortcuts import render

# Create your views here.

blog/templates/blog/application.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <link href="https://fonts.googleapis.com/css2?family=El+Messiri:wght@400;600&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/materialize.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/tooplate.css' %}">

<meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

<div class="topnav">
  <a class="active" href="{% url 'home' %}">الصفحة الرئيسية</a>
  {% if not request.user.is_authenticated %}
  <a href="{% url 'new1' %}">حساب جديد </a>
  {% endif%}
  {% if not request.user.is_authenticated %}
  <a href="{% url 'log1' %}">تسجيل الدخول </a>
  {% endif%}
  <a href="{% url 'ans1' %}">أجب</a>
  {% if request.user.is_authenticated %}
  <a href="{% url 'pro1' %}"> الملف الشخصي</a>
  {% endif%}
  {% if request.user.is_authenticated %}
  <a href="{% url 'out1' %}">تسجيل الخروج</a>
  {% endif%}

</div>


</body>
</html>

<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Application - Input Form by Tooplate</title>

    <link href="https://fonts.googleapis.com/css2?family=El+Messiri:wght@400;600&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <link rel="stylesheet" href="css/materialize.min.css">
    <link rel="stylesheet" href="css/tooplate.css">
</head>

<body id="application">
    <div class="container">
            <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12  mx-auto">
                <header class="mt-5 mb-5 text-center">
                    <h3>اسأل هنا</h3>
                    <p class="tm-form-description">لكل سؤال جواب اطرح مايجول برأسك دون خجل</p>
                </header>
                <form action="{% url 'ask1' %}" method="post" enctype="multipart/form-data" class="tm-form-white tm-font-big">
                    {% csrf_token %}
                    <div class="tm-bg-white tm-form-pad-big">
                        <div class="text-right">
                            <label for="name" class="black-text mb-4 big">... استفسارك عن</label>
                            <input id="id_title" name="title" type="text" class="validate tm-input-white-bg">
                        </div>
                        <div class="text-right">
                            <label for="message" class="black-text mb-4 big">تفاصيل المشكلة</label>
                            <textarea class="p-3" name="text1" id="id_text1" cols="30" rows="4"></textarea>
                        </div>
                        <div class="form-group mb-2 col-xl-6 col-lg-6 col-md-6 col-12 pr-0 tm-form-group-2-col tm-form-group-2-col-r">
                    
                            <label for="file" class="black-text mb-4 big">أرفق صورة المشكلة</label>
                            <div class="file-field input-field">
                                <div class="btn btn-white">
                                    <span>تصفح</span>
                                    <input type="file" name="img">
                                </div>
                                <div class="file-path-wrapper">
                                    <input class="file-path validate" name="file" type="text" placeholder="بصيغة jpg">
                                </div>
                            </div>
                        </div>
                    
                        <div class="text-left mt-4">
                            <button type="submit" class="waves-effect btn-small btn-large-white">إرسال</button>
                        </div>

                    </div>
                </form>
            </div>
                
    
            <footer class="row tm-mt-big mb-3">
                <div class="col-xl-12">
                    <p class="text-center grey-text text-lighten-2 tm-footer-text-small">
                        Copyright &copy; 2020 H A C K 
                        
                    </p>
                </div>
            </footer>
    </div>

    <script src="js/jquery-3.2.1.slim.min.js"></script>
    <script src="js/materialize.min.js"></script>
    <script>
        $(document).ready(function () {
            $('select').formSelect();
        });
    </script>
</body>

</html>

blog/templates/blog/base_generic.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <link href="https://fonts.googleapis.com/css2?family=El+Messiri:wght@400;600&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/materialize.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/tooplate.css' %}">

<meta name="viewport" content="width=device-width, initial-scale=1">

</head>
<body>

<div class="topnav">
   <a class="active" href="index.html">الصفحة الرئيسية</a>
  <a  href="register.html">حساب جديد</a>
  <a href="survey.html">الملف الشخصي</a>
  <a href="application.html">اسأل هنا</a>
  <a href="signup.html">أجب</a>
</div>


</body>
</html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Login Form by Tooplate</title>
	
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=El+Messiri&display=swap">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/materialize.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/tooplate.css' %}">
    
    
    
</head>
{% block content %}

<body>



        <footer class="row tm-mt-big mb-5">
            <div class="col-xl-12 text-center">
                {% block content %}

                {% endblock content %}

                <p class="d-inline-block tm-bg-gray white-text py-2 tm-px-5">
                    Copyright &copy; 2020 H A C K 
                </p>
            </div>
        </footer>
    </div>
</body>
{% endblock content %}

</html>

blog/templates/blog/index.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <link href="https://fonts.googleapis.com/css2?family=El+Messiri:wght@400;600&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/materialize.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/tooplate.css' %}">

<meta name="viewport" content="width=device-width, initial-scale=1">

</head>
<body>

<div class="topnav">
  {% if not request.user.is_authenticated %}
  <a class="active" href="{% url 'new1' %}">حساب جديد </a>
  {% endif%}
  {% if not request.user.is_authenticated %}
  <a href="{% url 'log1' %}"> تسجيل الدخول </a>
  {% endif%}
  <a href="{% url 'ask1' %}">اسأل هنا</a>
  <a href="{% url 'ans1' %}">أجب</a>
  {% if request.user.is_authenticated %}
  <a href="{% url 'pro1' %}"> الملف الشخصي</a>
  {% endif%}
  {% if request.user.is_authenticated %}
  <a href="{% url 'out1' %}">تسجيل الخروج</a>
  {% endif%}

</div>


</body>
</html>
<html lang="en" dir="ltr" >

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Input HTML Form Pack by Tooplate</title>
   
    
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <link rel="stylesheet" href="css/materialize.min.css">
    <link rel="stylesheet" href="css/tooplate.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=El+Messiri&display=swap"> 
</head>

<body id="home">
    <div class="container tm-home-mt tm-home-container">
        <div class="row">
            <div class="col-12">
                <div class="tm-home-center">
                   <h1 class="tm-site-title"><p><b>هاك</b></p></h1> 
                   <p><h3 style="background-color:powderblue;" class="text-center">لديك استفسار ؟ تحتاج مساعدة؟</h3></p>
                   <p style="background-color:#cc9900;" class="text-center">هاك موقع يجيب على كل استفساراتك لاتتردد بالسؤال</p> 
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-xl-12 col-lg-6 col-md-6 col-sm-12">
                <div class="tm-home-left mt-3 font-weight-light">
                    <p class="tm-mb-35"></p>
                   
                </div>
            
        </div>
        </div>
    </div>
    <footer class="row tm-mt-big mb-3">
        <div class="col-xl-12 text-center font-weight-light">
            <p class="d-inline-block tm-bg-gray white-text py-2 tm-px-5">
                Copyright &copy; 2020 H A C K
            </p>
        </div>
    </footer>
</body>

</html>

blog/templates/blog/login.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <link href="https://fonts.googleapis.com/css2?family=El+Messiri:wght@400;600&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/materialize.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/tooplate.css' %}">

<meta name="viewport" content="width=device-width, initial-scale=1">

</head>
<body>

<div class="topnav">
  <a class="active" href="{% url 'home' %}">الصفحة الرئيسية</a>
  {% if not request.user.is_authenticated %}
  <a href="{% url 'new1' %}">حساب جديد </a>
  {% endif%}
  <a href="{% url 'ask1' %}">اسأل هنا</a>
  <a href="{% url 'ans1' %}">أجب</a>
  {% if request.user.is_authenticated %}
  <a href="{% url 'pro1' %}"> الملف الشخصي</a>
  {% endif%}
  {% if request.user.is_authenticated %}
  <a href="{% url 'out1' %}">تسجيل الخروج</a>
  {% endif%}

</div>


</body>
</html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Login Form by Tooplate</title>
	
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=El+Messiri&display=swap">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/materialize.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/tooplate.css' %}">
    
    
    
</head>

<body id="login">
    <div class="container">
            <div class="row">
                <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12  mx-auto">
                <header class="mb-5  text-center ">
                    <h3 class="mt-0 text-white font-weight-light ">تسجيل الدخول </h3>
                </header>             
                <form action="{% url 'logBack'%}" method="post" class="tm-bg-black p-5 h-100">
                    {%csrf_token%}

                    <div class="input-field">
                        <p dir = "rtl"  align="right">
                            <input placeholder="اسم المستخدم" id="username" name="username" type="text" class="validate">
                            </p>
                        </div>
                    
                    <div class="input-field mb-5">
                       <p dir = "rtl"  align="right">
                        <input placeholder="كلمة المرور" id="password" name="password" type="password" class="validate">
                        </p>
                    </div>
                    <div class="tm-flex-lr">
                        
                        <button  type="submit" class="waves-effect btn-small btn-large-white px-4 black-text  rounded-0 ">دخول</button>
                    </div>
                    <br><br>
                    <a href="#" class="white-text small">استرجاع كلمة المرور</a>
                    </br>
                </form>
            </div>
        </div>
              <div class="text-center mt-8">
            <div class="col-xl-7 col-lg-6 col-md-6 col-sm-12 ml-auto mr-6 text-left">
                <a href="{% url 'new1' %}" class="waves-effect btn-small btn-large-white px-4 black-text rounded-0">حساب جديد</a>
            </div>
            
        </div>
        <footer class="row tm-mt-big mb-5">
            <div class="col-xl-12 text-center">
                <p class="d-inline-block tm-bg-gray white-text py-2 tm-px-5">
                    Copyright &copy; 2020 H A C K 
                </p>
            </div>
        </footer>
    </div>

    <script src="js/jquery-3.2.1.slim.min.js"></script>
    <script src="js/materialize.min.js"></script>
    <script>
        $(document).ready(function () {
            $('select').formSelect();
        });
    </script>
</body>

</html>

blog/templates/blog/login2.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <link href="https://fonts.googleapis.com/css2?family=El+Messiri:wght@400;600&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/materialize.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/tooplate.css' %}">

<meta name="viewport" content="width=device-width, initial-scale=1">

</head>
<body>

<div class="topnav">
    <a class="active" href="{% url 'home' %}">الصفحة الرئيسية</a>
    {% if not request.user.is_authenticated %}
    <a href="{% url 'new1' %}">حساب جديد </a>
    {% endif%}
    <a href="{% url 'ask1' %}">اسأل هنا</a>
    <a href="{% url 'ans1' %}">أجب</a>
    {% if request.user.is_authenticated %}
    <a href="{% url 'pro1' %}"> الملف الشخصي</a>
    {% endif%}
    {% if request.user.is_authenticated %}
    <a href="{% url 'out1' %}">تسجيل الخروج</a>
    {% endif%}
  
</div>


</body>
</html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Login Form by Tooplate</title>
	
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=El+Messiri&display=swap">
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <link rel="stylesheet" href="css/materialize.min.css">
    <link rel="stylesheet" href="css/tooplate.css">
    
    
    
</head>

<body id="login">
    <div class="container">
            <div class="row">
                <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12  mx-auto">
                <header class="mb-5  text-center ">
                    <h3 class="mt-0 text-white font-weight-light ">تسجيل الدخول </h3>
                </header>             
                <form action="" method="post" class="tm-bg-black p-5 h-100">
                    <div class="input-field ">
                        <p dir ="rtl"  align="right">
                             <input placeholder="البريد الإلكتروني" id="email" name="email" type="email" class="validate">
                       </p>
                    </div>
                    
                    <div class="input-field mb-5">
                       <p dir = "rtl"  align="right">
                        <input placeholder="كلمة المرور" id="password" name="password" type="password" class="validate">
                        </p>
                         <p style="color:red;">خطأ في البريد الإلكتروني أو كلمة المرور. حاول مرة أخرى<p>
                    </div>
                    <div class="tm-flex-lr">
                        
                        <button type="submit" class="waves-effect btn-small btn-large-white px-4 black-text  rounded-0 ">دخول</button>
                    </div>
                    <br><br>
                    <a href="#" class="white-text small">استرجاع كلمة المرور</a>
                    </br>
                </form>
            </div>
        </div>
              <div class="text-center mt-8">
            <div class="col-xl-7 col-lg-6 col-md-6 col-sm-12 ml-auto mr-6 text-left">
                <a href="register.html" class="waves-effect btn-small btn-large-white px-4 black-text rounded-0">حساب جديد</a>
            </div>
        </div>
        <footer class="row tm-mt-big mb-5">
            <div class="col-xl-12 text-center">
                <p class="d-inline-block tm-bg-gray white-text py-2 tm-px-5">
                    Copyright &copy; 2020 H A C K 
                </p>
            </div>
        </footer>
    </div>

    <script src="js/jquery-3.2.1.slim.min.js"></script>
    <script src="js/materialize.min.js"></script>
    <script>
        $(document).ready(function () {
            $('select').formSelect();
        });
    </script>
</body>

</html>

blog/templates/blog/login3.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <link href="https://fonts.googleapis.com/css2?family=El+Messiri:wght@400;600&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/materialize.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/tooplate.css' %}">

<meta name="viewport" content="width=device-width, initial-scale=1">

</head>
<body>

<div class="topnav">
  <a class="active" href="{% url 'home' %}">الصفحة الرئيسية</a>
  {% if not request.user.is_authenticated %}
  <a href="{% url 'log1' %}">تسجيل الدخول </a>
  {% endif%}
  <a href="{% url 'ask1' %}">اسأل هنا</a>
  <a href="{% url 'ans1' %}">أجب</a>
  {% if request.user.is_authenticated %}
  <a href="{% url 'pro1' %}"> الملف الشخصي</a>
  {% endif%}
  {% if request.user.is_authenticated %}
  <a href="{% url 'out1' %}">تسجيل الخروج</a>
  {% endif%}

</div>


</body>
</html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Register - Input Form by Tooplate</title>
	
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=El+Messiri&display=swap">
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <link rel="stylesheet" href="css/materialize.min.css">
    <link rel="stylesheet" href="css/tooplate.css">
    
</head>

<body id="register">

    <div class="container">
        <div class="row tm-register-row">
            <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12  mx-auto">
            
                <header class="mb-5  text-center ">
                    <h3 class="mt-0 text-white ">إنشاء حساب جديد</h3>
                </header>

                <form action="{% url 'newBack' %}" method="post"  >
                    {%csrf_token%}
                   <div class="tm-bg-black tm-form-pad-big">
                      <div class="form-group mb-5">
                    <div class="input-field">
                        <p dir = "rtl"  align="right" style="color:red;"> الاسم المستخدم غير متاح<p>

                    <p dir = "rtl"  align="right">
                        <input placeholder="الاسم الأول " id="first_name" name="first_name" type="text" class="validate">
                        </p>
                        
                    </div>
                    <div class="input-field">
                    <p dir = "rtl"  align="right">
                        <input placeholder="الاسم الأخير" id="last_name" name="last_name" type="text" class="validate">
                        </p>
                    </div>
                    <div class="input-field">
                        <p dir = "rtl"  align="right">
                            <input placeholder="اسم المستخدم" id="username" name="username" type="text" class="validate">
                            </p>
                        </div>
                    <div class="input-field">
                    <p dir = "rtl"  align="right">
                        <input placeholder="البريد الإلكتروني" id="email" name="email" type="email" class="validate">
                        </p>
                    </div>
                    <div class="input-field">
                    <p dir = "rtl"  align="right">
                        <input placeholder="كلمة المرور" id="password" name="password" type="password" class="validate">
                        </p>
                    </div>
                    <div class="input-field">
                    <p dir = "rtl"  align="right">
                        <input placeholder="تأكيد كلمة المرور" id="password2" name="password2" type="password" class="validate">
                        </p>
                    </div>
                     <div class="input-field">
                     <p dir = "rtl"  align="right">
                        <input placeholder="رقم الجوال" id="phone" name="phone" type="tel" class="validate">
                        </p>
                         <div class="input-field">
                          <p dir = "rtl"  align="right">
                         <input placeholder="العمر" id="age" name="age" type="text" class="validate">
                        </p>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-6 pr-0 tm-pl-xs-0">
                        
                        </div>
                       <div class="text-center mt-5">
                        <button type="submit" class="waves-effect btn-small btn-large-white px-4 black-text">تسجيل</button>
                    </div> 
                    </div>
                  </div>
                    </div>
                </form>
            </div>
        </div>
        <footer class="row tm-mt-big mb-3">
            <div class="col-xl-12">
                <p class="text-center grey-text text-lighten-2 tm-footer-text-small">
                    Copyright &copy; 2020 H A C K 
                </p>
            </div>
        </footer>
    </div>

    <script src="js/jquery-3.2.1.slim.min.js"></script>
    <script src="js/materialize.min.js"></script>
    <script>
        $(document).ready(function () {
            $('select').formSelect();
        });
    </script>
</body>

</html>